apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-test-project
  labels:
    service: django-test-project
spec:
  replicas: 1
  selector:
    matchLabels:
      service: django-test-project
  template:
    metadata:
      labels:
        service: django-test-project

    spec:
      containers: 
      - name: django-test-project
        image: ankitnayan/django-test-project:v0.13
        imagePullPolicy: Always
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: AUTOWRAPT_BOOTSTRAP
            value: signoz
          - name: APP_NAME
            value: test_app
          - name: JAEGER_AGENT_HOST
            value: jaeger-agent
          - name: JAEGER_SERVICE_NAME
            value: test_app

      restartPolicy: Always
