apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-test-project
  labels:
    service: django-test-project
spec:
  replicas: 2
  selector:
    matchLabels:
      service: django-test-project
  template:
    metadata:
      labels:
        service: django-test-project

    spec:
      containers: 
      - name: django-test-project
        image: ankitnayan/django-test-project:v0.10
        imagePullPolicy: Always
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      restartPolicy: Always
