apiVersion: v1
kind: Service
metadata:
  labels:
    service: django-with-statsd
  name: django-with-statsd
spec:
  ports:
  # - protocol: UDP
  #   port: 8125
  #   name: statsd-metrics-udp
  # - protocol: TCP
  #   port: 9125
  #   name: statsd-metrics-tcp
  # - protocol: TCP
  #   port: 9102
  #   nodePort: 30001
  #   name: prometheus-metrics

  # - protocol: TCP
  #   port: 8000
  #   nodePort: 30000
  #   name: django-app
  # externalIPs: ["35.239.206.97"]
  # type: NodePort
  # selector:
  #   service: django-with-statsd

  - protocol: TCP
    port: 8000
    name: django-app
  type: LoadBalancer
  selector:
    service: django-with-statsd