apiVersion: v1
kind: Service
metadata:
  labels:
    service: django-test-project
  name: django-test-project
spec:
  ports:
  - protocol: TCP
    port: 8000
    name: django-test-project
  type: LoadBalancer
  selector:
    service: django-test-project
